In [2]:
import pandas as pd

In [3]:
data = {
    'Name': ['Ravi', 'Aman', 'Neha', 'Priya', 'Karan', 'Simran', 'Arjun', 'Meera'],
    'Marks': [85, 72, None, 91, 68, None, 78, 88],
    'Age': [20, 21, 19, None, 20, 22, None, 21],
    'City': ['Delhi', 'Pune', 'Mumbai', 'Delhi', None, 'Pune', 'Jaipur', 'Mumbai']
}
df = pd.DataFrame(data)
print(df)

     Name  Marks   Age    City
0    Ravi   85.0  20.0   Delhi
1    Aman   72.0  21.0    Pune
2    Neha    NaN  19.0  Mumbai
3   Priya   91.0   NaN   Delhi
4   Karan   68.0  20.0     NaN
5  Simran    NaN  22.0    Pune
6   Arjun   78.0   NaN  Jaipur
7   Meera   88.0  21.0  Mumbai

In [4]:
df.isnull()

    Name  Marks    Age   City
0  False  False  False  False
1  False  False  False  False
2  False   True  False  False
3  False  False   True  False
4  False  False  False   True
5  False   True  False  False
6  False  False   True  False
7  False  False  False  False

In [15]:
df[df.isnull().any(axis=1)]

     Name  Marks   Age    City
2    Neha    NaN  19.0  Mumbai
3   Priya   91.0   NaN   Delhi
4   Karan   68.0  20.0     NaN
5  Simran    NaN  22.0    Pune
6   Arjun   78.0   NaN  Jaipur

In [24]:
df.dropna(subset="City")

     Name  Marks   Age    City
0    Ravi   85.0  20.0   Delhi
1    Aman   72.0  21.0    Pune
2    Neha    NaN  19.0  Mumbai
3   Priya   91.0   NaN   Delhi
5  Simran    NaN  22.0    Pune
6   Arjun   78.0   NaN  Jaipur
7   Meera   88.0  21.0  Mumbai

In [29]:
df['Marks']=df['Marks'].fillna(df['Marks'].mean())
print(df)

     Name      Marks   Age    City
0    Ravi  85.000000  20.0   Delhi
1    Aman  72.000000  21.0    Pune
2    Neha  80.333333  19.0  Mumbai
3   Priya  91.000000   NaN   Delhi
4   Karan  68.000000  20.0     NaN
5  Simran  80.333333  22.0    Pune
6   Arjun  78.000000   NaN  Jaipur
7   Meera  88.000000  21.0  Mumbai

In [30]:
df['Age']=df['Age'].fillna(df['Age'].median())
print(df)

     Name      Marks   Age    City
0    Ravi  85.000000  20.0   Delhi
1    Aman  72.000000  21.0    Pune
2    Neha  80.333333  19.0  Mumbai
3   Priya  91.000000  20.5   Delhi
4   Karan  68.000000  20.0     NaN
5  Simran  80.333333  22.0    Pune
6   Arjun  78.000000  20.5  Jaipur
7   Meera  88.000000  21.0  Mumbai

In [31]:
df['City']=df['City'].fillna('Unknown')
print(df)

     Name      Marks   Age     City
0    Ravi  85.000000  20.0    Delhi
1    Aman  72.000000  21.0     Pune
2    Neha  80.333333  19.0   Mumbai
3   Priya  91.000000  20.5    Delhi
4   Karan  68.000000  20.0  Unknown
5  Simran  80.333333  22.0     Pune
6   Arjun  78.000000  20.5   Jaipur
7   Meera  88.000000  21.0   Mumbai

In [32]:
data = {
    'Name': ['Ravi', 'Aman', 'Ravi', 'Neha', 'Aman', 'Karan'],
    'Marks': [85, 72, 85, 91, 72, 68],
    'Age': [20, 21, 20, 19, 21, 22]
}

df = pd.DataFrame(data)

print(df)

    Name  Marks  Age
0   Ravi     85   20
1   Aman     72   21
2   Ravi     85   20
3   Neha     91   19
4   Aman     72   21
5  Karan     68   22

In [33]:
df.duplicated()

0    False
1    False
2     True
3    False
4     True
5    False
dtype: bool

In [35]:
df.drop_duplicates()

    Name  Marks  Age
0   Ravi     85   20
1   Aman     72   21
3   Neha     91   19
5  Karan     68   22

In [38]:
df=df.drop_duplicates(subset='Name',keep='first')
print(df)

    Name  Marks  Age
0   Ravi     85   20
1   Aman     72   21
3   Neha     91   19
5  Karan     68   22