# Pandas Revision

Syntax on `placement.csv`, practice on `food_orders.csv`.

In [2]:
import pandas as pd

df = pd.read_csv('placement.csv')      # syntax examples
food = pd.read_csv('food_orders.csv')  # practice

---
## 1. First look

In [3]:
# size: (rows, columns)
df.shape

(550, 12)

In [4]:
# numeric summary: count, mean, min, max
df.describe().round(2)

,cgpa,twelfth_percent,internships,projects,backlogs,prep_hours,communication_score,package_lpa
count,550.00,550.00,519.00,550.00,550.00,454.00,538.00,517.00
mean,7.36,77.60,1.30,2.56,0.68,153.15,6.27,4.71
std,0.98,10.12,1.18,1.49,1.10,86.06,1.69,3.48
min,5.00,55.00,0.00,0.00,0.00,16.00,1.10,0.00
25%,6.69,70.90,0.00,1.00,0.00,90.00,5.20,0.00
50%,7.40,77.90,1.00,2.00,0.00,134.00,6.30,6.01
75%,7.98,84.50,2.00,4.00,1.00,192.75,7.40,7.28
max,10.00,98.00,4.00,6.00,4.00,500.00,10.00,12.56

In [5]:
# column types and non-null counts
food.info()

<class 'pandas.DataFrame'>
RangeIndex: 612 entries, 0 to 611
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   order_id           612 non-null    str
 1   city               612 non-null    str
 2   cuisine            612 non-null    str
 3   day                612 non-null    str
 4   order_hour         612 non-null    int64
 5   quantity           612 non-null    int64
 6   distance_km        604 non-null    float64
 7   order_value        612 non-null    int64
 8   delivery_time_min  612 non-null    int64
 9   payment            612 non-null    str
 10  rating             505 non-null    float64
 11  tip                427 non-null    float64
 12  was_late           612 non-null    str
dtypes: float64(3), int64(4), str(6)
memory usage: 62.3 KB

### Practice

**Q1.** How many orders are in the file, and how many details are stored for each order?

In [6]:
food.shape

(612, 13)

**Q2.** Someone ordered food worth a small EMI. Find the biggest order value and the longest delivery time using one command.

In [7]:
food[['order_value','delivery_time_min']].max()

order_value          2354
delivery_time_min      63
dtype: int64

**Q3.** Which columns hold numbers and which hold text?

In [8]:
food.dtypes

order_id                 str
city                     str
cuisine                  str
day                      str
order_hour             int64
quantity               int64
distance_km          float64
order_value            int64
delivery_time_min      int64
payment                  str
rating               float64
tip                  float64
was_late                 str
dtype: object

In [50]:
food[['city','tip']]

          city   tip
0       Mumbai  15.0
1         Pune  15.0
2    Hyderabad   0.0
3        Delhi  20.0
4        Delhi  10.0
..         ...   ...
607       Pune  30.0
608  Bangalore   0.0
609     Mumbai  30.0
610       Pune   0.0
611  Bangalore  40.0

[593 rows x 2 columns]

In [58]:
food.iloc[6]

order_id                 ORD10066
city                    Hyderabad
cuisine              South Indian
day                           Mon
order_hour                     17
quantity                        2
distance_km                   1.3
order_value                   197
delivery_time_min              19
payment                      Cash
rating                        4.0
tip                          15.0
was_late                       No
value_per_item               98.0
Name: 6, dtype: object

---
## 2. Selecting

In [10]:
# one column
df['cgpa']

0      7.41
1      7.52
2      7.35
3      7.86
4      5.63
       ...
545    8.40
546    7.60
547    6.33
548    8.86
549    8.45
Name: cgpa, Length: 550, dtype: float64

In [11]:
# many columns: a list inside [ ]
df[['branch', 'cgpa', 'placed']].head()

  branch  cgpa placed
0     IT  7.41     No
1    CSE  7.52    Yes
2    CSE  7.35    Yes
3    CSE  7.86    Yes
4    CSE  5.63    Yes

In [12]:
# iloc: by position -> rows, columns
df.iloc[0:5, 0:3]

  student_id  cgpa  twelfth_percent
0     VS2821  7.41             78.5
1     VS3068  7.52             70.0
2     VS2940  7.35             78.3
3     VS3138  7.86             60.2
4     VS2670  5.63             88.3

In [13]:
# loc: by label -> rows, column names (both ends included)
df.loc[0:4, 'cgpa':'internships']

   cgpa  twelfth_percent branch  internships
0  7.41             78.5     IT          0.0
1  7.52             70.0    CSE          2.0
2  7.35             78.3    CSE          2.0
3  7.86             60.2    CSE          1.0
4  5.63             88.3    CSE          2.0

### Practice

**Q4.** The manager's eyes hurt after 13 columns. Show only `city`, `cuisine` and `order_value` for the first 10 orders.

In [14]:
food[['city','cuisine','order_value']].head(10)

        city       cuisine  order_value
0     Mumbai       Chinese          519
1       Pune       Chinese          295
2  Hyderabad       Chinese          744
3      Delhi      Desserts          370
4      Delhi        Burger          594
5     Mumbai       Biryani          933
6  Hyderabad  South Indian          197
7       Pune       Biryani         1482
8  Bangalore       Biryani          522
9       Pune  South Indian          233

**Q5.** The printer jammed and printed only rows 50 to 54, first 5 columns. Recreate that page using positions.

In [15]:
food.iloc[50:55, 0:5]

    order_id       city       cuisine  day  order_hour
50  ORD10161  Bangalore         Pizza  Sun          22
51  ORD10156       Pune      Desserts  Mon          21
52  ORD10160      Delhi      Desserts  Sat          20
53  ORD10310       Pune      Desserts  Sun          13
54  ORD10018     Mumbai  South Indian  Sat          18

**Q6.** Using labels, show rows 100 to 105 and every column from `city` to `order_hour`.

In [16]:
food.loc[100:105,'city':'order_hour']

          city       cuisine  day  order_hour
100       Pune       Biryani  Sat          12
101       Pune        Burger  Sun          21
102     Mumbai         Pizza  Thu          17
103  Bangalore       Biryani  Sun          19
104     Mumbai         Pizza  Sun          23
105     Mumbai  South Indian  Sun          13

---
## 3. Filtering and sorting

In [17]:
# one condition
df[df['cgpa']>8]

,student_id,cgpa,twelfth_percent,branch,internships,projects,backlogs,prep_hours,communication_score,hostel,placed,package_lpa
14,VS2701,9.01,64.8,ECE,1.0,0,1,NaN,4.8,Yes,Yes,6.70
16,VS3012,8.29,77.8,CSE,0.0,2,0,81.0,7.9,Yes,Yes,8.06
17,VS2892,8.84,86.3,Civil,1.0,2,0,132.0,3.4,No,Yes,5.77
18,VS2936,8.23,69.5,CSE,3.0,3,1,119.0,6.9,Yes,Yes,8.54
21,VS2930,8.07,83.1,Mech,1.0,2,0,120.0,9.5,Yes,Yes,5.38
...,...,...,...,...,...,...,...,...,...,...,...,...
537,VS2668,8.21,74.2,CSE,0.0,4,0,157.0,5.5,Yes,Yes,7.66
539,VS2966,8.45,80.9,Mech,2.0,2,1,90.0,7.6,No,Yes,7.31
545,VS2811,8.40,79.7,ECE,1.0,4,0,173.0,5.0,Yes,Yes,6.22
548,VS2796,8.86,78.2,ECE,3.0,1,0,259.0,6.4,Yes,Yes,7.51
549,VS2775,8.45,70.7,CSE,0.0,3,0,NaN,5.1,Yes,Yes,8.45

In [18]:
# two conditions: & is and, | is or, each in its own ( )
df[(df['cgpa'] > 8) & (df['backlogs'] == 0)]

,student_id,cgpa,twelfth_percent,branch,internships,projects,backlogs,prep_hours,communication_score,hostel,placed,package_lpa
16,VS3012,8.29,77.8,CSE,0.0,2,0,81.0,7.9,Yes,Yes,8.06
17,VS2892,8.84,86.3,Civil,1.0,2,0,132.0,3.4,No,Yes,5.77
21,VS2930,8.07,83.1,Mech,1.0,2,0,120.0,9.5,Yes,Yes,5.38
44,VS3139,8.85,81.2,Mech,0.0,3,0,194.0,7.4,No,Yes,6.89
47,VS2788,8.09,84.6,Mech,0.0,2,0,220.0,6.0,Yes,No,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...
534,VS3112,8.37,63.9,CSE,4.0,2,0,103.0,5.9,Yes,Yes,7.52
537,VS2668,8.21,74.2,CSE,0.0,4,0,157.0,5.5,Yes,Yes,7.66
545,VS2811,8.40,79.7,ECE,1.0,4,0,173.0,5.0,Yes,Yes,6.22
548,VS2796,8.86,78.2,ECE,3.0,1,0,259.0,6.4,Yes,Yes,7.51
549,VS2775,8.45,70.7,CSE,0.0,3,0,NaN,5.1,Yes,Yes,8.45

In [19]:
# value is one of many
df[df['branch'].isin(['CSE', 'IT'])]

# value inside a range (both ends included)
df[df['cgpa'].between(7, 8)]

,student_id,cgpa,twelfth_percent,branch,internships,projects,backlogs,prep_hours,communication_score,hostel,placed,package_lpa
0,VS2821,7.41,78.5,IT,0.0,6,1,188.0,4.3,No,No,0.00
1,VS3068,7.52,70.0,CSE,2.0,3,0,167.0,9.8,Yes,Yes,10.06
2,VS2940,7.35,78.3,CSE,2.0,0,3,199.0,4.8,Yes,Yes,NaN
3,VS3138,7.86,60.2,CSE,1.0,3,0,135.0,8.0,No,Yes,8.63
6,VS2971,7.79,74.7,CSE,0.0,4,0,NaN,7.3,Yes,No,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...
536,VS3032,7.53,83.5,ECE,0.0,2,3,20.0,6.7,No,No,0.00
542,VS2998,7.81,63.4,IT,4.0,4,0,89.0,5.1,Yes,Yes,8.52
543,VS2785,7.19,77.5,ECE,3.0,4,0,84.0,6.5,No,Yes,6.68
544,VS2948,7.18,87.2,ECE,NaN,1,1,296.0,4.2,Yes,No,0.00
546,VS3102,7.60,76.5,Civil,0.0,4,0,NaN,6.7,Yes,Yes,5.68

In [20]:
# count of each category
df['branch'].value_counts()

branch
CSE      167
IT       118
ECE      112
Mech     103
Civil     50
Name: count, dtype: int64

In [21]:
# sort, biggest first
df.sort_values('cgpa', ascending=False).head()

,student_id,cgpa,twelfth_percent,branch,internships,projects,backlogs,prep_hours,communication_score,hostel,placed,package_lpa
113,VS3148,10.00,93.9,Mech,3.0,3,0,190.0,6.8,Yes,Yes,9.17
500,VS2917,10.00,84.0,ECE,0.0,4,0,58.0,6.3,No,Yes,8.54
265,VS2702,9.95,86.5,CSE,2.0,0,0,248.0,7.0,No,Yes,10.03
185,VS3124,9.85,63.8,CSE,0.0,4,0,87.0,7.5,Yes,Yes,8.77
157,VS2747,9.78,85.3,ECE,2.0,2,0,NaN,5.3,Yes,Yes,NaN

### Practice

**Q7.** Biryani at 2 AM is not hunger, it is a lifestyle. Count the Biryani orders placed between midnight and 3 AM (hours 0 to 3).

In [22]:
food[(food['cuisine'] == 'Biryani') & (food['order_hour'].between(0, 3))]['cuisine'].value_counts()

cuisine
Biryani    35
Name: count, dtype: int64

**Q8.** Someone in Pune is clearly throwing a party. Show Pune orders worth more than 1000 rupees. How many?

In [23]:
food[(food['order_value']>1000) & (food['city']=='Pune')].shape[0]

23

**Q9.** A food blogger survives only on Pizza and Burger. How many such orders are there?

In [24]:
food[(food['cuisine']=='Pizza')& (food['cuisine']=='Burger')].shape[0]

0

**Q10.** How many deliveries fell in the *"bhaiya, kahan ho?"* zone of 30 to 45 minutes?

In [25]:
food[food['delivery_time_min'].between(30,45)].shape[0]

222

**Q11.** Does anyone still pay in cash? Count the orders by payment method.

In [26]:
food[food['payment']=='Cash'].shape[0]

95

**Q12.** Someone definitely ordered for the whole hostel. Show the 5 biggest orders with `city`, `cuisine`, `quantity` and `order_value`.

In [27]:
food.sort_values(['city', 'cuisine', 'quantity', 'order_value'], ascending=False).head()

,order_id,city,cuisine,day,order_hour,quantity,distance_km,order_value,delivery_time_min,payment,rating,tip,was_late
203,ORD10428,Pune,South Indian,Mon,19,8,4.1,1014,30,UPI,4.0,20.0,No
271,ORD10448,Pune,South Indian,Mon,20,6,2.1,775,18,UPI,5.0,35.0,No
453,ORD10143,Pune,South Indian,Sat,22,5,3.0,793,18,UPI,5.0,30.0,No
485,ORD10114,Pune,South Indian,Sun,18,5,1.8,728,21,Card,5.0,15.0,No
174,ORD10401,Pune,South Indian,Sat,21,5,3.0,700,27,Cash,3.0,25.0,No

**Q13.** Which delivery partners were basically The Flash? Show the 5 fastest deliveries with `city`, `distance_km` and `delivery_time_min`.

In [28]:
food.sort_values(['city','delivery_time_min','distance_km'],ascending=True).head()

,order_id,city,cuisine,day,order_hour,quantity,distance_km,order_value,delivery_time_min,payment,rating,tip,was_late
240,ORD10423,Bangalore,South Indian,Wed,12,3,0.8,398,12,UPI,4.0,45.0,No
440,ORD10304,Bangalore,Biryani,Thu,0,2,0.9,389,13,UPI,4.0,50.0,No
326,ORD10541,Bangalore,Chinese,Wed,1,2,0.6,447,15,Cash,3.0,NaN,No
537,ORD10560,Bangalore,Burger,Fri,22,5,1.5,944,15,Card,NaN,35.0,No
133,ORD10212,Bangalore,Desserts,Sun,0,5,1.5,736,16,Cash,4.0,35.0,No

---
## 4. Cleaning

In [29]:
# blanks per column
df.isnull().sum()

student_id              0
cgpa                    0
twelfth_percent         0
branch                  0
internships            31
projects                0
backlogs                0
prep_hours             96
communication_score    12
hostel                  0
placed                  0
package_lpa            33
dtype: int64

In [30]:
# repeated rows
print(df.duplicated().sum())

# remove repeated rows
df_clean = df.drop_duplicates()

0

In [31]:
# remove rows where one column is blank
df_clean = df_clean.dropna(subset=['internships'])

# fill blanks with a value
df_clean['prep_hours'] = df_clean['prep_hours'].fillna(0)

# change the type
df_clean['internships'] = df_clean['internships'].astype(int)

In [32]:
# new column from existing columns
df_clean['cgpa_percent'] = (df_clean['cgpa'] * 9.5).round(1)
df_clean[['cgpa', 'cgpa_percent']].head()

   cgpa  cgpa_percent
0  7.41          70.4
1  7.52          71.4
2  7.35          69.8
3  7.86          74.7
4  5.63          53.5

### Practice

**Q14.** Count the blanks in every column.

In [33]:
food.isnull().sum()

order_id               0
city                   0
cuisine                0
day                    0
order_hour             0
quantity               0
distance_km            8
order_value            0
delivery_time_min      0
payment                0
rating               107
tip                  185
was_late               0
dtype: int64

**Q15.** The app got confused and saved some orders twice. How many repeated rows are there?

In [34]:
food.duplicated().value_counts()

False    600
True      12
Name: count, dtype: int64

**Q16.** Remove the repeated orders before customers get charged twice. Print the shape.

In [35]:
food = food.drop_duplicates()
food.shape

(600, 13)

**Q17.** GPS failed for some orders, so the delivery partner took the scenic route. Remove the rows with a blank `distance_km` and print the shape.

In [36]:
food=food.dropna(subset='distance_km')
food['distance_km'].isnull().sum()

np.int64(0)

**Q18.** A blank tip means no tip, and one sad delivery partner. Fill the blanks in `tip` with 0 and make it a whole number.

In [37]:
food['tip']=food['tip'].fillna(0)
food['tip'].isnull().sum()

np.int64(0)

**Q19.** Add a column `value_per_item`: order value divided by quantity, rounded.

In [38]:
food['value_per_item'] = (food['order_value'] / food['quantity']).round()

---
## 5. Grouping and saving

In [39]:
# average per group
df.groupby('branch')['cgpa'].mean()

branch
CSE      7.484431
Civil    7.341200
ECE      7.377054
IT       7.183051
Mech     7.342233
Name: cgpa, dtype: float64

In [40]:
# sorted, highest first
df.groupby('branch')['cgpa'].mean().sort_values(ascending=False)

branch
CSE      7.484431
ECE      7.377054
Mech     7.342233
Civil    7.341200
IT       7.183051
Name: cgpa, dtype: float64

In [41]:
# other numbers per group
df.groupby('branch')['cgpa'].max()
df.groupby('branch')['internships'].sum()
df.groupby('branch')['student_id'].count()

branch
CSE      167
Civil     50
ECE      112
IT       118
Mech     103
Name: student_id, dtype: int64

In [42]:
# save to a file, without the index column
df_clean.to_csv('placement_clean.csv',index=False)

### Practice

**Q20.** Which city is the stingiest tipper? Find the average tip per city, lowest first.

In [43]:
food.groupby('city')['tip'].mean().sort_values(ascending=False)

city
Bangalore    29.694656
Mumbai       23.089431
Pune         20.354610
Hyderabad    16.363636
Delhi        12.575758
Name: tip, dtype: float64

**Q21.** Is the weekend really a party? Find the average order value for each day, highest first.

In [44]:
food.groupby('day')['order_value'].mean().sort_values(ascending=False)

day
Sat    666.465753
Sun    663.818182
Fri    588.244444
Tue    562.818182
Mon    560.800000
Wed    558.819672
Thu    540.590909
Name: order_value, dtype: float64

**Q22.** Does a late delivery earn an angry rating? Compare the average rating of late and on-time orders.

In [45]:
food.groupby('rating')['delivery_time_min'].mean()

rating
2.0    36.894737
3.0    30.786408
4.0    27.448454
5.0    26.848837
Name: delivery_time_min, dtype: float64

**Q23.** Which city holds the record for the single biggest order after cleaning? Find the highest order value in each city.

**Q24.** Which payment method brings in the most money? Find the total order value for each payment method.

**Q25.** Which cuisine is the nation's favourite? Count the orders for each cuisine.

**Q26.** Save the cleaned data as `food_orders_clean.csv` without the index column.

---
*Q16 to Q19 change `food`. Run them only once, in order.*