# 🐼 **Pandas Practice 1**

---

# ⚙️ **0. Setup**

### _Run this cell first — it loads the dataset used throughout the notebook._

---

In [1]:
import pandas as pd
import numpy as np

url = "https://raw.githubusercontent.com/skm22/Introduction_To_Machine_Learning/main/Data/mpg.csv"
df = pd.read_csv(url)
df.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
0,18.0,8,307.0,130.0,3504,12.0,70,usa,chevrolet chevelle malibu
1,15.0,8,350.0,165.0,3693,11.5,70,usa,buick skylark 320
2,18.0,8,318.0,150.0,3436,11.0,70,usa,plymouth satellite
3,16.0,8,304.0,150.0,3433,12.0,70,usa,amc rebel sst
4,17.0,8,302.0,140.0,3449,10.5,70,usa,ford torino

# 🔍 **1. Basic Exploration**

### _`.head(n)` / `.tail(n)` → first/last rows | `.shape` → (rows, cols) | `.columns` → column names | `.dtypes` → column data types_

---

**Q1.1 Display the first 7 rows and the last 4 rows of `df`.**

In [5]:
df.head(7)
df.tail(4)

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
394,44.0,4,97.0,52.0,2130,24.6,82,europe,vw pickup
395,32.0,4,135.0,84.0,2295,11.6,82,usa,dodge rampage
396,28.0,4,120.0,79.0,2625,18.6,82,usa,ford ranger
397,31.0,4,119.0,82.0,2720,19.4,82,usa,chevy s-10

**Q1.2 Print the shape of `df`, the list of column names, and the dtype of each column.**

In [7]:
df.shape

(398, 9)

**Q1.3 Use `.info()` and `.describe()` to get a summary of the dataset. What does `.describe()` tell you about the `mpg` column?**

In [10]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   mpg           398 non-null    float64
 1   cylinders     398 non-null    int64
 2   displacement  398 non-null    float64
 3   horsepower    392 non-null    float64
 4   weight        398 non-null    int64
 5   acceleration  398 non-null    float64
 6   model_year    398 non-null    int64
 7   origin        398 non-null    str
 8   name          398 non-null    str
dtypes: float64(4), int64(3), str(2)
memory usage: 28.1 KB

**Q1.4 Unpack `.shape` into two variables (e.g. `rows, cols = df.shape`) and print how many rows and columns the dataset has.**

In [12]:
# Write your code here
rows,cols=df.shape
print(rows,cols)

398 9

# 🎯 **2. Selecting Columns & Rows**

### _`df['col']` → single column (Series) | `df[['a','b']]` → multiple columns (DataFrame) | `.loc[rows, cols]` → label-based | `.iloc[rows, cols]` → position-based_

---

**Q2.1 Select only the `mpg` and `name` columns and store in a new variable.**

In [14]:
# Write your code here
mpg_and_name_df = df[["mpg", "name"]]
print(mpg_and_name_df.head())

    mpg                       name
0  18.0  chevrolet chevelle malibu
1  15.0          buick skylark 320
2  18.0         plymouth satellite
3  16.0              amc rebel sst
4  17.0                ford torino

**Q2.2 Use `.loc` to get rows 5 to 10 (inclusive) showing only the `mpg`, `cylinders`, and `horsepower` columns.**

In [15]:
# Write your code here
subset_df = df.loc[5:10, ["mpg", "cylinders", "horsepower"]]
print(subset_df)

     mpg  cylinders  horsepower
5   15.0          8       198.0
6   14.0          8       220.0
7   14.0          8       215.0
8   14.0          8       225.0
9   15.0          8       190.0
10  15.0          8       170.0

**Q2.3 Use `.iloc` to get the first 3 rows and the last 2 columns of `df`.**

In [16]:
# Write your code here
subset_df = df.iloc[:3, -2:]
print(subset_df)

  origin                       name
0    usa  chevrolet chevelle malibu
1    usa          buick skylark 320
2    usa         plymouth satellite

**Q2.4 Select the `mpg` column using both `df['mpg']` and `df.mpg`, and confirm that both give the same result.**

In [18]:
# Write your code here
col_bracket = df["mpg"]
col_dot = df.mpg
is_identical = col_bracket.equals(col_dot)
print(col_dot)

0      18.0
1      15.0
2      18.0
3      16.0
4      17.0
       ...
393    27.0
394    44.0
395    32.0
396    28.0
397    31.0
Name: mpg, Length: 398, dtype: float64

# 🧮 **3. Filtering / Boolean Indexing**

### _`df[df['col'] > x]` → condition-based filtering | combine conditions with `&` (and) / `|` (or), each wrapped in `()`_

---

**Q3.1 Filter and display all cars with `mpg` greater than 30.**

In [19]:
# Write your code here
high_mpg_cars = df[df["mpg"] > 30]
print(high_mpg_cars)

      mpg  cylinders  displacement  horsepower  weight  acceleration  \
53   31.0          4          71.0        65.0    1773          19.0
54   35.0          4          72.0        69.0    1613          18.0
129  31.0          4          79.0        67.0    1950          19.0
131  32.0          4          71.0        65.0    1836          21.0
144  31.0          4          76.0        52.0    1649          16.5
..    ...        ...           ...         ...     ...           ...
390  32.0          4         144.0        96.0    2665          13.9
391  36.0          4         135.0        84.0    2370          13.0
394  44.0          4          97.0        52.0    2130          24.6
395  32.0          4         135.0        84.0    2295          11.6
397  31.0          4         119.0        82.0    2720          19.4

     model_year  origin                 name
53           71   japan  toyota corolla 1200
54           71   japan          datsun 1200
129          74   japan          datsun b210
131          74   japan  toyota corolla 1200
144          74   japan        toyota corona
..          ...     ...                  ...
390          82   japan     toyota celica gt
391          82     usa    dodge charger 2.2
394          82  europe            vw pickup
395          82     usa        dodge rampage
397          82     usa           chevy s-10

[85 rows x 9 columns]

**Q3.2 Filter all cars from `origin == 'japan'` that also have `horsepower` less than 100.**

In [20]:
# Write your code here
filtered_cars = df[(df["origin"] == "japan") & (df["horsepower"] < 100)]
print(filtered_cars)

      mpg  cylinders  displacement  horsepower  weight  acceleration  \
14   24.0          4         113.0        95.0    2372          15.0
18   27.0          4          97.0        88.0    2130          14.5
29   27.0          4          97.0        88.0    2130          14.5
31   25.0          4         113.0        95.0    2228          14.0
53   31.0          4          71.0        65.0    1773          19.0
..    ...        ...           ...         ...     ...           ...
382  34.0          4         108.0        70.0    2245          16.9
383  38.0          4          91.0        67.0    1965          15.0
384  32.0          4          91.0        67.0    1965          15.7
385  38.0          4          91.0        67.0    1995          16.2
390  32.0          4         144.0        96.0    2665          13.9

     model_year origin                   name
14           70  japan  toyota corona mark ii
18           70  japan           datsun pl510
29           71  japan           datsun pl510
31           71  japan          toyota corona
53           71  japan    toyota corolla 1200
..          ...    ...                    ...
382          82  japan         toyota corolla
383          82  japan            honda civic
384          82  japan     honda civic (auto)
385          82  japan          datsun 310 gx
390          82  japan       toyota celica gt

[71 rows x 9 columns]

**Q3.3 Filter all cars with `cylinders == 4` and `model_year >= 78`.**

In [21]:
# Write your code here
filtered_cars = df[(df["cylinders"] == 4) & (df["model_year"] >= 78)]
print(filtered_cars)

      mpg  cylinders  displacement  horsepower  weight  acceleration  \
244  43.1          4          90.0        48.0    1985          21.5
245  36.1          4          98.0        66.0    1800          14.4
246  32.8          4          78.0        52.0    1985          19.4
247  39.4          4          85.0        70.0    2070          18.6
248  36.1          4          91.0        60.0    1800          16.4
..    ...        ...           ...         ...     ...           ...
393  27.0          4         140.0        86.0    2790          15.6
394  44.0          4          97.0        52.0    2130          24.6
395  32.0          4         135.0        84.0    2295          11.6
396  28.0          4         120.0        79.0    2625          18.6
397  31.0          4         119.0        82.0    2720          19.4

     model_year  origin                             name
244          78  europe  volkswagen rabbit custom diesel
245          78     usa                      ford fiesta
246          78   japan                 mazda glc deluxe
247          78   japan                   datsun b210 gx
248          78   japan                 honda civic cvcc
..          ...     ...                              ...
393          82     usa                  ford mustang gl
394          82  europe                        vw pickup
395          82     usa                    dodge rampage
396          82     usa                      ford ranger
397          82     usa                       chevy s-10

[103 rows x 9 columns]

**Q3.4 Filter all cars where `origin` is **not** `'usa'`, using the `~` (NOT) operator.**

In [ ]:
# Write your code here
non_usa_cars = df[~(df["origin"] == "usa")]
print(non_usa_cars)

# ↕️ **4. Sorting**

### _`.sort_values('col')` → ascending by default | `ascending=False` → descending | pass a list of columns for multi-level sort_

---

**Q4.1 Sort the dataset by `mpg` in descending order and show the top 5 most fuel-efficient cars (name + mpg).**

In [22]:
# Write your code here
top_5_mpg = df.nlargest(5, "mpg")[["name", "mpg"]]

print(top_5_mpg)

                     name   mpg
322             mazda glc  46.6
329   honda civic 1500 gl  44.6
325  vw rabbit c (diesel)  44.3
394             vw pickup  44.0
326    vw dasher (diesel)  43.4

**Q4.2 Sort the dataset first by `weight` (ascending) and then by `horsepower` (descending).**

In [23]:
# Write your code here
sorted_df = df.sort_values( by=["weight", "horsepower"], ascending=[True, False])
print(sorted_df)

      mpg  cylinders  displacement  horsepower  weight  acceleration  \
54   35.0          4          72.0        69.0    1613          18.0
144  31.0          4          76.0        52.0    1649          16.5
343  39.1          4          79.0        58.0    1755          16.9
345  35.1          4          81.0        60.0    1760          16.1
53   31.0          4          71.0        65.0    1773          19.0
..    ...        ...           ...         ...     ...           ...
95   12.0          8         455.0       225.0    4951          11.0
90   12.0          8         429.0       198.0    4952          11.5
42   12.0          8         383.0       180.0    4955          11.5
103  11.0          8         400.0       150.0    4997          14.0
44   13.0          8         400.0       175.0    5140          12.0

     model_year origin                      name
54           71  japan               datsun 1200
144          74  japan             toyota corona
343          81  japan            toyota starlet
345          81  japan          honda civic 1300
53           71  japan       toyota corolla 1200
..          ...    ...                       ...
95           73    usa  buick electra 225 custom
90           73    usa  mercury marquis brougham
42           71    usa         dodge monaco (sw)
103          73    usa          chevrolet impala
44           71    usa       pontiac safari (sw)

[398 rows x 9 columns]

**Q4.3 Sort the dataset alphabetically by `name` (A to Z) and display the first 5 rows.**

In [24]:
# Write your code here
sorted_by_name = df.sort_values(by="name", ascending=True).head(5)
print(sorted_by_name)

      mpg  cylinders  displacement  horsepower  weight  acceleration  \
96   13.0          8         360.0       175.0    3821          11.0
9    15.0          8         390.0       190.0    3850           8.5
66   17.0          8         304.0       150.0    3672          11.5
315  24.3          4         151.0        90.0    3003          20.1
257  19.4          6         232.0        90.0    3210          17.2

     model_year origin                     name
96           73    usa  amc ambassador brougham
9            70    usa       amc ambassador dpl
66           72    usa       amc ambassador sst
315          80    usa              amc concord
257          78    usa              amc concord

# 🧹 **5. Handling Missing Values**

### _`.isnull().sum()` → count missing values per column | `.fillna(value)` → fill missing | `.dropna()` → drop rows/cols with missing values_

---

**Q5.1 Check how many missing values exist in each column of `df`.**

In [25]:
# Write your code here
missing_counts = df.isna().sum()
print(missing_counts)

mpg             0
cylinders       0
displacement    0
horsepower      6
weight          0
acceleration    0
model_year      0
origin          0
name            0
dtype: int64

**Q5.2 Fill any missing values in the `horsepower` column with the column's mean value.**

In [26]:
# Write your code here
mean_hp = df['horsepower'].mean()
df['horsepower'] = df['horsepower'].fillna(mean_hp)
print(df['horsepower'].isna().sum())

0

**Q5.3 Find the total number of missing values in the entire dataset (a single number) using `.isnull().sum().sum()`.**

In [ ]:
# Write your code here
total_missing = df.isnull().sum().sum()
print(total_missing)

Total missing values in the dataset: 0

# 🛠️ **6. Adding, Transforming & Dropping Columns**

### _Create a column by assignment: `df['new'] = ...` | `.apply(func)` → apply a function/lambda element-wise | `.drop(columns=[...])` → remove columns_

---

**Q6.1 Add a new column `weight_kg` by converting `weight` (in lbs) to kilograms (1 lb = 0.4536 kg).**

In [29]:
# Write your code here
df['weight_kg'] = df['weight'] * 0.4536
print(df[['name','weight']])

                          name  weight
0    chevrolet chevelle malibu    3504
1            buick skylark 320    3693
2           plymouth satellite    3436
3                amc rebel sst    3433
4                  ford torino    3449
..                         ...     ...
393            ford mustang gl    2790
394                  vw pickup    2130
395              dodge rampage    2295
396                ford ranger    2625
397                 chevy s-10    2720

[398 rows x 2 columns]

**Q6.2 Add a new column `efficiency` using `.apply()` with a lambda: label a car `'Good'` if `mpg >= 25`, `'Average'` if `15 <= mpg < 25`, else `'Poor'`.**

In [ ]:
# Write your code here
df[efficiency]=df['mpg'.apply]

**Q6.3 Drop the `name` column and store the result in a new DataFrame called `df_numeric`.**

In [ ]:
# Write your code here

**Q6.4 Add a new column `hp_per_weight` by dividing `horsepower` by `weight` for every row.**

In [31]:
# Write your code here
df_numeric=df.drop(columns=['name'])
print(df_numeric)

      mpg  cylinders  displacement  horsepower  weight  acceleration  \
0    18.0          8         307.0       130.0    3504          12.0
1    15.0          8         350.0       165.0    3693          11.5
2    18.0          8         318.0       150.0    3436          11.0
3    16.0          8         304.0       150.0    3433          12.0
4    17.0          8         302.0       140.0    3449          10.5
..    ...        ...           ...         ...     ...           ...
393  27.0          4         140.0        86.0    2790          15.6
394  44.0          4          97.0        52.0    2130          24.6
395  32.0          4         135.0        84.0    2295          11.6
396  28.0          4         120.0        79.0    2625          18.6
397  31.0          4         119.0        82.0    2720          19.4

     model_year  origin  weight_kg
0            70     usa  1589.4144
1            70     usa  1675.1448
2            70     usa  1558.5696
3            70     usa  1557.2088
4            70     usa  1564.4664
..          ...     ...        ...
393          82     usa  1265.5440
394          82  europe   966.1680
395          82     usa  1041.0120
396          82     usa  1190.7000
397          82     usa  1233.7920

[398 rows x 9 columns]

# 📊 **7. GroupBy & Aggregation**

### _`.groupby('col')` → split by group | `.mean()`, `.max()`, `.count()` → aggregate | `.agg({...})` → different aggregation per column_

---

**Q7.1 Group by `origin` and find the average `mpg` for each origin.**

In [32]:
# Write your code here
avg_mpg_by_origin = df.groupby("origin")["mpg"].mean()
print(avg_mpg_by_origin)

origin
europe    27.891429
japan     30.450633
usa       20.083534
Name: mpg, dtype: float64

**Q7.2 Group by `cylinders` and find the average `mpg` and the maximum `horsepower` for each group using `.agg()`.**

In [ ]:
# Write your code here
grouped_df = df.groupby("cylinders").agg(avg_mpg=("mpg", "mean"),max_horsepower=("horsepower", "max"))
print(grouped_df)

             avg_mpg  max_horsepower
cylinders
3          20.550000           110.0
4          29.286765           115.0
5          27.366667           103.0
6          19.985714           165.0
8          14.963107           230.0

**Q7.3 Group by `model_year` and count how many cars were made each year.**

In [34]:
# Write your code here
cars_per_year = df.groupby("model_year")["name"].count()
print(cars_per_year)

model_year
70    29
71    28
72    28
73    40
74    27
75    30
76    34
77    28
78    36
79    29
80    29
81    29
82    31
Name: name, dtype: int64

**Q7.4 Group by both `origin` and `cylinders` together, and find the average `mpg` for each combination.**

In [ ]:
# Write your code here
avg_mpg = df.groupby(["origin", "cylinders"])["mpg"].mean()
print(avg_mpg)

origin  cylinders
europe  4            28.411111
        5            27.366667
        6            20.100000
japan   3            20.550000
        4            31.595652
        6            23.883333
usa     4            27.840278
        6            19.663514
        8            14.963107
Name: mpg, dtype: float64

# 🔢 **8. Value Counts & Unique Values**

### _`.value_counts()` → frequency of each unique value | `.unique()` → array of distinct values | `.nunique()` → count of distinct values_

---

**Q8.1 Use `.value_counts()` to see how many cars come from each `origin`.**

In [36]:
# Write your code here
origin_counts = df['origin'].value_counts()
print(origin_counts)

origin
usa       249
japan      79
europe     70
Name: count, dtype: int64

**Q8.2 Find the number of unique values in `cylinders` and print all the unique values in `model_year`.**

In [37]:
# Write your code here
num_unique_cylinders = df['cylinders'].nunique()
print(num_unique_cylinders)

5

**Q8.3 Using `.value_counts()`, find which `model_year` has the highest number of cars.**

In [ ]:
# Write your code here

# 🔤 **9. String Operations**

### _`.str.split()`, `.str.upper()`, `.str.contains()` etc. work on string (object) columns via the `.str` accessor_

---

**Q9.1 Create a new column `brand` by extracting the first word from the `name` column (e.g. 'chevrolet chevelle malibu' → 'chevrolet') using `.str.split()`.**

In [ ]:
# Write your code here

**Q9.2 Create a new column `name_upper` by converting the `name` column to uppercase using `.str.upper()`.**

In [ ]:
# Write your code here

**Q9.3 Use `.str.contains('ford', case=False)` to filter all cars whose name contains 'ford'.**

In [ ]:
# Write your code here

# 🧾 **10. Duplicates & Renaming**

### _`.duplicated()` → boolean mask of duplicate rows | `.drop_duplicates()` → remove them | `.rename(columns={...})` → rename columns_

---

**Q10.1 Check whether `df` has any duplicate rows using `.duplicated()`, then remove them with `.drop_duplicates()`.**

In [ ]:
# Write your code here

**Q10.2 Rename the `model_year` column to `year` and the `horsepower` column to `hp`.**

In [ ]:
# Write your code here

**Q10.3 Rename every column name to uppercase in one line, using `.rename(columns=...)` with a dictionary comprehension.**

In [ ]:
# Write your code here

# 🔗 **11. Merge & Concat**

### _`pd.merge(df1, df2, on='col')` → join two DataFrames on a common column | `pd.concat([df1, df2])` → stack DataFrames together_

---

**Q11.1 Create a small lookup DataFrame mapping `origin` codes to full names (`'usa' -> 'United States'`, `'japan' -> 'Japan'`, `'europe' -> 'Europe'`) and merge it with `df` on the `origin` column.**

In [ ]:
# Write your code here

**Q11.2 Create two smaller DataFrames — the first 5 rows and the last 5 rows of `df` — and combine them back together using `pd.concat()`.**

In [ ]:
# Write your code here

**Q11.3 From the merged DataFrame in Q11.1, display only the `name`, `origin`, and the new full-name column for the first 5 rows.**

In [ ]:
# Write your code here

# 💾 **12. Exporting Data**

### _`.to_csv('filename.csv', index=False)` → save a DataFrame to a CSV file_

---

**Q12.1 Filter cars with `mpg > 25`, then save the result to a new file called `efficient_cars.csv` (without the index column).**

In [ ]:
# Write your code here

**Q12.2 Filter cars with `cylinders == 8` and save them to a file called `eight_cylinder_cars.csv`.**

In [ ]:
# Write your code here

**Q12.3 Read back the `efficient_cars.csv` file you saved in Q12.1 using `pd.read_csv()`, and confirm it loaded correctly by checking its shape.**

In [ ]:
# Write your code here