<h1>Assignment 1 — Inspecting a New Dataset

In [3]:
import pandas as pd
t = pd.read_csv('Titanic-Dataset.csv')

<h4>Q1 Load the dataset into t. How many rows and how many columns does it have?

In [4]:
t = pd.read_csv('Titanic-Dataset.csv')
print(t.shape)

(891, 12)

<h4>Q2 Print all the column names. Pick any three and write in a comment what you think each one holds.

In [5]:
print(t.columns)

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='str')

<h4>Q3 Display the first 7 rows and the last 3 rows.

In [6]:
t.head(7)
t.tail(3)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

<h4>Q4 Run t.info(). Some columns have fewer values than the total number of rows. Write down which
columns those are, and how many values are missing from each. ★

In [7]:
t.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    str
 4   Sex          891 non-null    str
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    str
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    str
 11  Embarked     889 non-null    str
dtypes: float64(2), int64(5), str(5)
memory usage: 83.7 KB

<h4>Q5 Run t.describe(). It shows fewer columns than info() listed. Write down two columns it left out,
and explain why.

In [8]:
t.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

<h4>Q6 For the class column, answer all three questions below using a different function for each:
a) how many different values are there?
b) what are they?
c) how many passengers fall into each one?

In [9]:
t['Pclass'].nunique()
t['Pclass'].unique()
t['Pclass'].value_counts()

Pclass
3    491
1    216
2    184
Name: count, dtype: int64

<h4>Q7 Find how many passengers were male and how many were female

In [10]:
t['Sex'].value_counts()

Sex
male      577
female    314
Name: count, dtype: int64

<h4>Q8 In describe(), look at the age column. Compare its mean with its 50% value. Which is larger, and
what does that suggest about the passengers' ages? ★

In [11]:
t['Age'].describe()

count    714.000000
mean      29.699118
std       14.526497
min        0.420000
25%       20.125000
50%       28.000000
75%       38.000000
max       80.000000
Name: Age, dtype: float64

<h4>Q9 (Challenge) The age column has missing values. Using only shape and info(), work out what
percentage of age values are missing. Write the number in a comment.

In [12]:
t.shape
t.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    str
 4   Sex          891 non-null    str
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    str
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    str
 11  Embarked     889 non-null    str
dtypes: float64(2), int64(5), str(5)
memory usage: 83.7 KB